name: "Pylint action"
description: "Runs pylint and sends errors in a PR message"
author: Gabriel Gazola Milan
inputs:
  path:
    description: "Path of files (default is **/*.py)"
    required: true
    default: "**/*.py"
  fail:
    description: "If true, the action will fail if pylint finds errors (default is true)"
    required: true
    default: true
  pr-message:
    description: "If true, the action will send a PR message if pylint finds errors (default is true)"
    required: true
    default: true
runs:
  using: "node12"
  main: "index.js"
